### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by KihongK** [openthermalcamera/Android-Application#4]
Is this project only possible with modules made with [openthermalcamera/HW-PCB](https://github.com/openthermalcamera/HW-PCB)?

Is it not possible with the mlx90640 module sold on pimoroni.com ??

**Comment by themarpe** [comment]
Hey @KihongK 

Yes, as is, the STM32 onboard carries out the communication with the MLX90640, so its required.

But note that MLX90640 can be then taken from anywhere
